apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBRc7y2+ut1r9roTepbjpSYG+/6orCRx7zpVdd/VJxqqbygbleemjYi9FePeMF9M0hzNJlryL8KNUkdjeLv9sTDZpbWqdEomjXibPbYBK87uMWRyF3vCeLNwSRobzKVliHwsk89liGKJka80Fh++F3snJlo4R0ktztEt8Ug+FY0CzO5F5Inkd+K4XSzawI1tFGVO0tHQv85kh48fdmxR7WaQ+qYHvW//K8Lde3VYeGNxWHCUInUTAcD8IIbzfIU44yneOwsuwpIBj2mb/EiOf9EsyqNtefAWqUXqQdb3fIBhhEGIhHkbuf7sdKmg2hWKCF+a9qIxBWMeUCG5rNSe7KrDi9FUMi3pewV4xS3O9Uaq04Tq+tc4XHceialTq1cmUe+p91ikQ21ZEqv53CWW/x76Y+NDNZzk1CqefrP5G4lI4ytJBJHRFOcoXkBCw51bnelQ2ECgweANsnWDFOtHFVQl8qAsMp1NTNIBCOqxLThnJXBv6xQpVll7dIYef+hW9ts6A/x8MxGVXfKuGeSy3m8P3JswTFWZ1mb7r55ALvYs2T7sC2rSHESYoSMupsUXZ0sYwr0fz6t8xbo9dnkR20ooNkZzkf/KIQsTIjXoSfbggFfFE314tOiQk+Bpj4DVIihTdKKNoiJL0Ia03NbLTsr8btOBmofWUVtujDk01/b9MSdppVOIWjj2yMwVlkdSLWJut+2SG/IpA==
    DB_USER: AgBeOag0OGvAsolxtyrFMNq7LLwVD4kN9Qgs2nAtJIf2uC2AnOjzQoCihGtPCetyMxGee07SDeI3+6jtED2IYVSLtBnC/qZVLojmZq3KfzS6FE+TSODM1vxC++EBiYwNmQWTsnZlVkKdvJ/R0hY1fOOmYI6R9V+3Xmv5+XLOPCUhe/OMVL6x9Q+4mo97LJf2vmIuFW9IhnkrNYwmIzqUxvEwVtCSpsnNX3f9ClzTT0d80p5Sb/1f4yr7WnQ5d+0orjBh8oWLYTdiYjvFrvCkxVhYrWT0X14KCjyULgv9otPuvZEYRzh7LJToDUuSeKY/uCCstQO1dDpPohsd1sV0LqdcYKbCIY58d6kpZbTftTeOfGrfL/smsv3EL+AMelRcin/X0nOPGOKXPoQBJGz0jd2fE8mkh+uKfVrRgUPFbySM6qIiN1AN5yUoxGQNzDkcQ4MNj8t/E50iBEAEaJLTMDB6rKXG0uTf3vq2tJaBkZcaKsDXqdnbRnYQI1rL4GldV4oZhcg3uJh8ox3yR/X4Qm4/RJ1WPq3YV00af9of3ymDMlrXW9nD/PhChhiZUCzGaQ99iGuMtHH/xFusEUsjUGgscGEJ6GKGQjabXp5FGt3OhLu0yp2teTE7KVnM36fRh1pGOkRWij7Af8w6iv5zGzHGJzGdox1KCh8S822Iqoo4UXKLDIWk6oU8Z4JJ9HZlqEEZjGFfgVRb/w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

