apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
  namespace: sccm
  annotations:
    argocd.argoproj.io/sync-wave: "270"
spec:
  dnsNames:
    - "*.itzroks-662001wt63-t223fo-4b4a324f027aea19c5cbc0c3275c4656-0000.us-south.containers.appdomain.cloud"
  privateKey:
    algorithm: RSA
    size: 2048   
  usages:
    - server auth
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: self-signed-sccm-issuer
  secretName: ibm-sccm-certs-secret
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: .keyStorePassword
        name: ibm-sccm-secret
  subject:
    organizations:
    - ibm
