apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-sccm-issuer
  namespace: sccm
  annotations:
    argocd.argoproj.io/sync-wave: "265"
  labels:
    gitops.tier.group: cntk
spec:
  selfSigned: {}